# Generated by Django 4.1.5 on 2023-01-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('titleName', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('authors', models.CharField(blank=True, max_length=100, null=True)),
                ('totalPage', models.CharField(blank=True, max_length=100, null=True)),
                ('ratings', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=250, null=True)),
                ('publishedDate', models.CharField(blank=True, max_length=100, null=True)),
                ('pageRead', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('state', models.CharField(choices=[('completed', 'Completed'), ('plan to read', 'Plan to Read'), ('reading', 'Reading')], default='plan to read', max_length=100)),
            ],
        ),
    ]
