# Generated by Django 4.1.5 on 2023-01-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RLibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.CharField(choices=[('completed', 'Completed'), ('plan-to-read', 'Plan-to-Read'), ('reading', 'Reading')], default='plan-to-read', max_length=100),
        ),
    ]
